/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.JOptionPane;
import java.util.HashMap;


public class Pertemuan_6 extends javax.swing.JFrame {
    HashMap<String, Integer> hargaMenu = new HashMap<>();
    int totalSemua = 0;

    /**
     * Creates new form Pertemuan_6
     */
    public Pertemuan_6() {
        initComponents();
        hargaMenu.put("Nasi Goreng", 10000);
        hargaMenu.put("Mie Ayam", 12000);
        hargaMenu.put("Bakso", 13000);
        hargaMenu.put("Sate Ayam", 15000);
        hargaMenu.put("Bebek Goreng", 20000);
        hargaMenu.put("Ayam Goreng", 17000);
        
        hargaMenu.put("Es Teh", 4000);
        hargaMenu.put("Kopi", 5000);
        hargaMenu.put("Soda", 10000);
        hargaMenu.put("Jus Jeruk", 5000);
        hargaMenu.put("Air Mineral", 4000);
        hargaMenu.put("Es Coklat", 9000);
        struk_pesanan.setText(
    "======== STRUK PESANAN ========\n" +
    "No Meja : \n" +
    "Nama    : \n" +
    "--------------------------------\n"
    );
        //dropdown_kategori.removeAllItems();
        dropdown_kategori.addItem("Makanan");
        dropdown_kategori.addItem("Minuman");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        Button_tambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeja_filed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pemesanan_filed = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dropdown_kategori = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_menu = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txthargaMenu = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        struk_pesanan = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        Button_tambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_tambah.setText("ambah");
        Button_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_tambahActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("APLIKASI PEMESANAN MAKANAN ");

        jLabel2.setText("No. Meja :");

        jLabel3.setText("Pemesan :");

        jLabel4.setText("Kategori  :");

        dropdown_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        dropdown_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_kategoriActionPerformed(evt);
            }
        });

        jLabel5.setText("Menu      :");

        list_menu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "menu 1", "menu 2", "menu 3", "menu 4", "menu 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_menu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_menuValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_menu);

        jButton1.setBackground(new java.awt.Color(153, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("PESAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Harga      :");

        txthargaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaMenuActionPerformed(evt);
            }
        });

        struk_pesanan.setColumns(20);
        struk_pesanan.setRows(5);
        jScrollPane2.setViewportView(struk_pesanan);

        jLabel7.setText("Struk Pesanan      :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 140, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeja_filed)
                                    .addComponent(pemesanan_filed)
                                    .addComponent(dropdown_kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txthargaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeja_filed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pemesanan_filed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dropdown_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthargaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane2))
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropdown_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_kategoriActionPerformed
        String kategori=dropdown_kategori.getSelectedItem().toString();
        String[]data=null;
        if(kategori.equals("Makanan")){
            data=new String[]{"Nasi Goreng", "Mie Ayam", "Bakso","Sate Ayam","Bebek Goreng","Ayam Goreng"};
        }
        else if(kategori.equals("Minuman")){
            data = new String[]{"Es Teh", "Kopi", "Soda","Jus Jeruk","Air Mineral","Es Coklat"};
        }
            list_menu.setListData(data);
    }//GEN-LAST:event_dropdown_kategoriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nomorMeja=nomeja_filed.getText();
        String namaPemesan=pemesanan_filed.getText();
        String menu=list_menu.getSelectedValue();
        if(menu == null){
            JOptionPane.showMessageDialog(null, "Pilih menu dulu!");
            return;
        }
        int harga = hargaMenu.get(menu);
        // tambah total
        totalSemua += harga;
        // tampil ulang header + data
        struk_pesanan.setText(
            "======== STRUK PESANAN ========\n" +
            "No Meja : " + nomeja_filed.getText() + "\n" +
            "Nama    : " + pemesanan_filed.getText() + "\n" +
            "--------------------------------\n"
        );
        // isi menu
        struk_pesanan.append(
            String.format("%-15s Rp %d\n", menu, harga)
        );
        // total
        struk_pesanan.append("--------------------------------\n");
        struk_pesanan.append("Total : Rp " + totalSemua + "\n");
        String gabung="No Meja :"+nomorMeja+"\nNama Pemesan : "+namaPemesan+"\nMenu : "+menu+"\nHarga : "+ harga;
        JOptionPane.showMessageDialog(this,gabung);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txthargaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaMenuActionPerformed

    private void list_menuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_menuValueChanged
        String menu = list_menu.getSelectedValue();
        int harga = 0;
        if(menu.equals("Nasi Goreng")){
            harga = 10000;
        }else if(menu.equals("Mie Ayam")){
            harga = 12000;
        }else if(menu.equals("Bakso")){
            harga = 6000;
        }else if(menu.equals("Ayam Goreng")){
            harga = 17000;
        }else if(menu.equals("Sate Ayam")){
            harga = 20000;
        }else if(menu.equals("Bebek Goreng")){
            harga = 25000;
        }else if(menu.equals("Es Teh")){
            harga = 4000;
        }else if(menu.equals("Kopi")){
            harga = 5000;
        }else if(menu.equals("Soda")){
            harga = 10000;
        }else if(menu.equals("Jus Jeruk")){
            harga = 5000;
        }else if(menu.equals("Air Mineral")){
            harga = 4000; 
        }else if(menu.equals("Es Coklat")){
            harga = 9000;
        }
        txthargaMenu.setText(String.valueOf(harga));
        hargaMenu.get("Rp " + harga);
    }//GEN-LAST:event_list_menuValueChanged

    private void Button_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_tambahActionPerformed
           
    }//GEN-LAST:event_Button_tambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pertemuan_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pertemuan_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pertemuan_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pertemuan_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pertemuan_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_tambah;
    private javax.swing.JComboBox<String> dropdown_kategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JList<String> list_menu;
    private javax.swing.JTextField nomeja_filed;
    private javax.swing.JTextField pemesanan_filed;
    private javax.swing.JTextArea struk_pesanan;
    private javax.swing.JTextField txthargaMenu;
    // End of variables declaration//GEN-END:variables
}
